# This is a basic workflow to help you get started with Actions

name: Post merge

# Controls when the workflow will run
on:
  # Triggers the workflow on push
  push:
    branches: [ "main", "master" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  allChecks:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      - name:  Run all checks
        run: ./gradlew check --stracktrace

      - uses: actions/upload-artifact@v2
        with:
          name: lint-report.html
          path: app/build/reports/lint-results.html
          
      - name:  Upload Test results
      - uses: actions/upload-artifact@v1
        with:
          name: test-report.html
          path: app/build/reports/tests/testDebugUnitTest/index.html
          
  instrumentationTests:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Run Instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 35
          script: ./gradlew connectedCheck --stracktrace

          
  deploy: 
   runs-on: ubuntu-latest
   # Не выполнится пока не будут выполнены следующие tasks
   needs: [allChecks, instrumentationTests]

   steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Build Snapshot
        run: ./gradlew assemble --stracktrace

      - uses: actions/upload-artifact@v2
        with:
          name: app-release-SNAPSHOT.apk
          path: app/build/outputs/apk/release/app-release-unsigned.apk
